version: '3'

services:
  web:
    image: nginx:1.15.6-alpine
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7.19
    env_file:
      - ./docker/mysql/.env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
